devices/urls.py
from django.urls import path
from . import views

app_name = 'devices'

urlpatterns = [
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('devices/create/', views.DeviceCreateView.as_view(), name='device_create'),
    path('devices/<slug:slug>/', views.DeviceDetailView.as_view(), name='device_detail'),
    path('devices/<slug:slug>/update/', views.DeviceUpdateView.as_view(), name='device_update'),
    path('devices/<slug:slug>/delete/', views.DeviceDeleteView.as_view(), name='device_delete'),
    path('devices/<slug:slug>/macaddress_create/', views.MacAddressCreateView.as_view(), name='macaddress_create'),
    path('devices/<slug:slug>/macaddress_<int:pk>/update/', views.MacAddressUpdateView.as_view(), name='macaddress_update'),
    path('devices/<slug:slug>/macaddresses_<int:pk>/delete/', views.MacAddressDeleteView.as_view(), name='macaddress_delete'),
]

devices_policies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # To have correct redirection when we try to access something when we are not logged in
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # Local apps
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('', include('devices.urls')),
    path('', include('policies.urls')),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutPageView.as_view(), name='about'), 
    path('', views.HomePageView.as_view(), name='homepage'),
]

policies/urls.py
from django.urls import path
from . import views

app_name = 'policies'

urlpatterns = [
    path('policies/', views.PolicyListView.as_view(), name='policies'),
    path('policies/create/', views.PolicyCreateView.as_view(), name='policy_create'),
    path('policies/<int:pk>/', views.PolicyDetailView.as_view(), name='policy_detail'),
    path('policies/<int:pk>/update/', views.PolicyUpdateView.as_view(), name='policy_update'),
    path('policies/<int:pk>/delete/', views.PolicyDeleteView.as_view(), name='policy_delete'),
]

devices/models.py
from django.conf import settings
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse


    
class Device(models.Model):
    registrator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    manufacturer = models.CharField(max_length=45, null=False, blank=False, verbose_name='Manufacturer', db_index=True)
    name = models.CharField(unique=True, max_length=45, null=False, blank=False, verbose_name='Model Name', db_index=True)
    slug = AutoSlugField(populate_from=['manufacturer', 'name'], unique=True)
    website = models.URLField(max_length=255, verbose_name='Website')
    policies = models.ManyToManyField('policies.Policy', related_name='devices', blank=True)
    
    class Meta:
        db_table = 'Device'
        ordering = ('manufacturer','name')
        
        
    def __str__(self):
        return "{}: {}".format(self.manufacturer, self.name)
    
    def get_absolute_url(self):
        return reverse('devices:device_detail', kwargs={'slug':self.slug})
    

class MacAddress(models.Model):
    registrator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mac_address = models.CharField(unique=True, verbose_name='MAC Address', max_length=17, null=False, blank=False)
    device = models.ForeignKey('Device', on_delete=models.CASCADE, blank=True, related_name='macAddresses')

    class Meta:
        db_table = 'MacAddress'
        verbose_name_plural = 'Mac_Addresses'
        
    def __str__(self):
        return "{}: {}".format(self.mac_address, self.device.name)
    
    def get_absolute_url(self):
        return reverse('devices:device_detail', kwargs={'slug': self.device.slug})
    
    def get_update_url(self):
        return reverse('devices:macaddress_update', kwargs={'slug':self.device.slug, 'pk':self.id})
    
    def get_delete_url(self):
        return reverse('devices:macaddress_delete', kwargs={'slug':self.device.slug, 'pk': self.id})
    
    

devices/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Device, MacAddress
from policies.models import Policy



class DeviceListView(LoginRequiredMixin, ListView):
    model = Device
    context_object_name = 'device_list'
    template_name = 'devices/device_list.html'
    
    def get_queryset(self):
        if self.request.user.is_superuser:
            return Device.objects.all()
        else:
            return Device.objects.filter(registrator=self.request.user)


class DeviceDetailView(LoginRequiredMixin, DetailView):
    model = Device
    context_object_name = 'device'
    template_name = 'devices/device_detail.html'


class DeviceCreateView(LoginRequiredMixin, CreateView):
    model = Device
    template_name = 'devices/device_form.html'
    fields = ('manufacturer', 'name', 'website', 'policies',)
    
    def clean_name(self):
        return self.cleaned_date['name'].replace('','_')
    
    def form_valid(self, form):
        form.instance.registrator = self.request.user
        return super().form_valid(form)
    
    
class DeviceUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Device
    template_name = 'devices/device_form_update.html'
    fields = ('manufacturer', 'name', 'website', 'policies',)
    
    def test_func(self):
        obj = self.get_object()
        return obj.registrator == self.request.user or self.request.user.is_superuser
    
class DeviceDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Device
    template_name = 'devices/device_confirm_delete.html'
    success_url = reverse_lazy('devices:devices')
    
    def test_func(self):
        obj = self.get_object()
        return obj.registrator == self.request.user or self.request.user.is_superuser

    
    
class MacAddressCreateView(LoginRequiredMixin, CreateView):
    model = MacAddress
    template_name = 'devices/mac_address_form.html'
    fields = ('mac_address',)
    
    def get_context_data(self, **kwargs):
        context = super(MacAddressCreateView, self).get_context_data(**kwargs)
        context['slug'] = self.kwargs['slug']
        return context
    
    def form_valid(self, form):
        form.instance.registrator = self.request.user or self.request.user.is_superuser
        form.instance.device = Device.objects.get(slug=self.kwargs['slug'])
        return super().form_valid(form)
    
    
class MacAddressUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = MacAddress
    template_name = 'devices/mac_address_form_update.html' 
    fields = ('mac_address',)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slug'] = self.kwargs['slug']
        context['pk'] = self.kwargs['pk']
        return context
    
    def test_func(self):
        obj = self.get_object()
        return obj.registrator == self.request.user or self.request.user.is_superuser
    
    
class MacAddressDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = MacAddress
    template_name = 'devices/mac_address_confirm_delete.html'
    success_url = reverse_lazy('devices:devices')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slug'] = self.kwargs['slug']
        context['pk'] = self.kwargs['pk']
        return context
    
    def test_func(self):
        obj = self.get_object()
        return obj.registrator == self.request.user or self.request.user.is_superuser

    

devices/templates/devices/base_devices.html
{% extends parent_template|default:"base.html" %}
{% load static %}
{% block css %}{{ block.super }}
  <link rel="stylesheet" href="{% static 'devices/css/devices_base.css' %}">
{% endblock css %}

devices/templates/devices/device_confirm_delete.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Delete Device
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form action="{% url 'devices:device_delete' device.slug %}" method="post">
  {% csrf_token %}
  <p>
    Are you sure you want to delete the device {{ device.name }}?
  </p>
  <a href="{{ device.get_absolute_url }}" class="btn btn-primary">Cancel</a>
  <button class="btn btn-danger" type="submit">Delete Device</button>  
</form>
{% endblock content %}

devices/templates/devices/device_detail.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% block title %}
{{ block.super }} - {{ device.manufacturer|title}} {{ device.name|title}}
{% endblock title %} 

{% block css %}{% endblock css %}

{% block content %}
  <div class="container">
    <h3 class="text-info"> 
      {{ device.manufacturer|title}} {{ device.name|title}}
      <a href="{% url 'devices:device_update' device.slug %}" class="btn btn-warning">Edit</a>
      <a href="{% url 'devices:device_delete' device.slug %}" class="btn btn-danger">Delete</a>
    </h3>
    <hr>
  </div>
  <div class="container">
    <h5 class="text-success">Website: <a class=text-info href="{{ device.website }}" target="_blank">
      {{ device.website }}</a></h5>
  </div>
  <br>
  <div class=container>
    {% if device.policies.all %}
      <p>
        <h3 class="text-info">Polic{{ device.policies.count|pluralize:"y,ies"}}</h3>
        {% for policy in device.policies.all %}
          <h5>
            <li class="text-info list-group-item list-group-item-info">
              Policy {{ policy.id }}&nbsp;<a href="{{ policy.get_absolute_url }}" class="btn btn-info">Show</a>
            </li>
          </h5>
        {% endfor %}
      </p>
    {% else %}
      <p>
        <em class="text-info">No policies assigned to this device...</em> 
      </p> 
    {% endif %}
    <p>
      <h5><a href="{% url 'policies:policy_create' %}">+ Add a Policy</a></h5>
    </p>
  </div>
  <hr>
  <br>
  <div class="container">
    {% if device.macAddresses.all %}
      <p>
        <h3 class="text-info">MAC Address{{ device.macAddresses.count|pluralize:"es" }}</h3>
        {% for mac_address in device.macAddresses.all %}
          <h5><li class="text-info list-group-item list-group-item-info">{{ mac_address.mac_address }}&nbsp;
            <a href="{% url 'devices:macaddress_update' device.slug mac_address.pk %}" class="btn btn-warning">Edit</a>
            <a href="{% url 'devices:macaddress_delete' device.slug mac_address.pk %}" class="btn btn-danger">Delete</a></h5>
          </li>
        {% endfor %}
      </p>  
    {% else %}
    <p>
      <li class="text-info list-group-item list-group-item-info">
        <em class="text-info">No mac addresses assigned to this device...</em>
      </li> 
    </p>
    {% endif %}
    <p>
      <h5> <a href="{% url 'devices:macaddress_create' device.slug %}">+ Add a MAC Address</a></h5>
    </p>
  </div>  
{% endblock content %}

devices/templates/devices/device_form.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Create a New Device
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form class="" action="{% url 'devices:device_create' %}" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
<button class="btn btn-success" type="submit">Create New Device</button>    
</form>

{% endblock content %}

devices/templates/devices/device_form_update.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Update Device
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form class="" action="{% url 'devices:device_update' device.slug %}" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit" name="">Update Device</button>  
</form>

{% endblock content %}

devices/templates/devices/device_list.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% block title %}
{{ block.super }} - Devices
{% endblock title %}

{% block css %}

{% endblock css %}

{% block content %}
  <p>
    <h5><a href="{% url 'devices:device_create' %}">+Add a New Device</a></h5>
  </p>
  {% for device in device_list %}
  <p>
    <h3> 
      <a href="{{ device.get_absolute_url }}">{{ device.manufacturer|title}} {{ device.name|title}}</a>
      <a href="{% url 'devices:device_update' device.slug %}" class="btn btn-warning">Edit</a>
      <a href="{% url 'devices:device_delete' device.slug %}" class="btn btn-danger">Delete</a>
    </h3>
  </p>
  <p>
    {% empty %}
      <em class="text-info">No Devices Available...</em>
  </p>  
  {% endfor %}
{% endblock content %}

devices/templates/devices/mac_address_confirm_delete.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Delete MAC Address
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form action="{{ mac_address.get_delete_url }}" method="post">
  {% csrf_token %}
  <p>
    Are you sure you want to delete the mac address {{ mac_address.mac_address }}?
  </p>
  <a href="{% url 'devices:device_detail' slug %}" class="btn btn-primary">Cancel</a>
  <button class="btn btn-danger" type="submit">Delete MAC Address</button>  
</form>
{% endblock content %}

devices/templates/devices/mac_address_form.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Create a New MAC Address
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
  <form  action="{% url 'devices:macaddress_create' slug %}" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Create MAC Address</button>  
</form>
{% endblock content %}

devices/templates/devices/mac_address_form_update.html
{% extends parent_template|default:"devices/base_devices.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Update MAC Address
{% endblock title %}

{% block css %}{% endblock css %}


{% block content %}
<form class="" action="{{ mac_address.get_update_url }}" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit" name="">Update MAC Address</button>  
</form>

{% endblock content %}