devices/urls.py
from django.urls import path
from . import views

app_name = 'devices'

urlpatterns = [
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('devices/create/', views.DeviceCreateView.as_view(), name='device_create'),
    path('devices/<slug:slug>/', views.DeviceDetailView.as_view(), name='device_detail'),
    path('devices/<slug:slug>/update/', views.DeviceUpdateView.as_view(), name='device_update'),
    path('devices/<slug:slug>/delete/', views.DeviceDeleteView.as_view(), name='device_delete'),
    path('devices/<slug:slug>/macaddress_create/', views.MacAddressCreateView.as_view(), name='macaddress_create'),
    path('devices/<slug:slug>/macaddress_<int:pk>/update/', views.MacAddressUpdateView.as_view(), name='macaddress_update'),
    path('devices/<slug:slug>/macaddresses_<int:pk>/delete/', views.MacAddressDeleteView.as_view(), name='macaddress_delete'),
]

devices_policies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # To have correct redirection when we try to access something when we are not logged in
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # Local apps
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('', include('devices.urls')),
    path('', include('policies.urls')),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutPageView.as_view(), name='about'), 
    path('', views.HomePageView.as_view(), name='homepage'),
]

policies/urls.py
from django.urls import path
from . import views

app_name = 'policies'

urlpatterns = [
    path('policies/', views.PolicyListView.as_view(), name='policies'),
    path('policies/create/', views.PolicyCreateView.as_view(), name='policy_create'),
    path('policies/<int:pk>/', views.PolicyDetailView.as_view(), name='policy_detail'),
    path('policies/<int:pk>/update/', views.PolicyUpdateView.as_view(), name='policy_update'),
    path('policies/<int:pk>/delete/', views.PolicyDeleteView.as_view(), name='policy_delete'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Rasprotect{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://kit.fontawesome.com/705f104950.js" crossorigin="anonymous"></script>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  {% block css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% endblock css %}
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">  
        <a href="{% url 'pages:homepage' %}" class="navbar-brand font-weight-bold"><span class="fas fa-home fa-2x fa-pull-left" style="color:white"></span></a>
        <a href="{% url 'pages:homepage' %}" class="navbar-brand font-weight-bold">RaspProtect</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
          <div class="navbar-nav">
            <a href="{% url 'devices:devices' %}" class="nav-item nav-link">Devices</a>
            <a href="{% url 'policies:policies' %}" class="nav-item nav-link">Policies</a>
            <a href="{% url 'pages:about' %}" class="nav-item nav-link">About</a>
          </div>
          <div class="navbar-nav">
            {% block navblock %}
            {% endblock navblock %}
            {% if user.is_authenticated %}
              <span class="fas fa-user fa-2x fa-pull-left" style="color:green"></span>  
              <a href="{% url 'password_change' %}" class="btn btn-outline-success nav-link">Change Password</a>
              <a href="{% url 'logout' %}" class="btn btn-outline-success nav-link">Logout</a>
            {% else %}
              <span class="fas fa-user fa-2x fa-pull-left" style="color:green"></span> 
              <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
              <a href="{% url 'users:signup' %}" class="btn btn-outline-success">Signup</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <div class="jumbotron">
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <footer class="text-muted">
    <div class="container text-center">
      <p>©️ RaspProtect {% now "Y" %}</p>
    </div>
  </footer>
  <!-- JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>
{% endblock content %}