devices/urls.py
from django.urls import path
from . import views

app_name = 'devices'

urlpatterns = [
    path('devices/', views.DeviceListView.as_view(), name='devices'),
    path('devices/create/', views.DeviceCreateView.as_view(), name='device_create'),
    path('devices/<slug:slug>/', views.DeviceDetailView.as_view(), name='device_detail'),
    path('devices/<slug:slug>/update/', views.DeviceUpdateView.as_view(), name='device_update'),
    path('devices/<slug:slug>/delete/', views.DeviceDeleteView.as_view(), name='device_delete'),
    path('devices/<slug:slug>/macaddress_create/', views.MacAddressCreateView.as_view(), name='macaddress_create'),
    path('devices/<slug:slug>/macaddress_<int:pk>/update/', views.MacAddressUpdateView.as_view(), name='macaddress_update'),
    path('devices/<slug:slug>/macaddresses_<int:pk>/delete/', views.MacAddressDeleteView.as_view(), name='macaddress_delete'),
]

devices_policies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # To have correct redirection when we try to access something when we are not logged in
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/', include('django.contrib.auth.urls')),
    # Local apps
    path('users/', include('users.urls')),
    path('', include('pages.urls')),
    path('', include('devices.urls')),
    path('', include('policies.urls')),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutPageView.as_view(), name='about'), 
    path('', views.HomePageView.as_view(), name='homepage'),
]

policies/urls.py
from django.urls import path
from . import views

app_name = 'policies'

urlpatterns = [
    path('policies/', views.PolicyListView.as_view(), name='policies'),
    path('policies/create/', views.PolicyCreateView.as_view(), name='policy_create'),
    path('policies/<int:pk>/', views.PolicyDetailView.as_view(), name='policy_detail'),
    path('policies/<int:pk>/update/', views.PolicyUpdateView.as_view(), name='policy_update'),
    path('policies/<int:pk>/delete/', views.PolicyDeleteView.as_view(), name='policy_delete'),
]

policies/models.py
from django.conf import settings
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.urls import reverse

class Policy(models.Model):
    registrator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    perm_dest_ports = models.CharField(max_length=255, blank=True, null=True, verbose_name='Permitted Destination Ports', help_text='Write the port numbers and seperate them using ",".')
    perm_dest_ips = models.CharField(max_length=512, blank=True, null=True, verbose_name='Permitted Destination IPs', help_text='Write the IP Addresses and seperate them using ",".')
    max_size_packet = models.PositiveIntegerField(verbose_name='Maximum Size Packet', null=True, blank=True)
    max_data_rate = models.PositiveIntegerField(verbose_name='Maximum Data Rate', null=True, blank=True)
    starting_time = models.TimeField(blank=True, null=True, help_text='Starting time of the policy.')
    ending_time = models.TimeField(blank=True, null=True, help_text='Ending time of the policy.' )
    restriction_level = models.CharField(max_length=1, null=False, blank=False, verbose_name='Restriction Level', help_text='Values from 1 to 5, with 1 for the least and 5 for the most restricted.')
    
    class Meta:
        db_table = 'Policy'
        verbose_name_plural = 'Policies'
    
    def __str__(self):
        return "Policy Number: {}".format(self.pk)
    
    def get_absolute_url(self):
        return reverse('policies:policy_detail', kwargs={'pk': self.pk})
    
    def get_update_url(self):
        return reverse('policies:policy_update', kwargs={'pk':self.pk})
    
    def get_delete_url(self):
        return reverse('policies:policy_delete', kwargs={'pk': self.pk})

policies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Policy
from django.urls import reverse_lazy


class PolicyListView(LoginRequiredMixin, ListView):
    model = Policy
    context_object_name = 'policy_list'
    template_name = 'policies/policy_list.html'


class PolicyDetailView(LoginRequiredMixin, DetailView):
    model = Policy
    context_object_name = 'policy'
    template_name = 'policies/policy_detail.html'
    

class PolicyCreateView(LoginRequiredMixin, CreateView):
    model = Policy
    template_name = 'policies/policy_form.html'
    fields = ('perm_dest_ports', 'perm_dest_ips', 'max_size_packet', 'max_data_rate', 'starting_time', 'ending_time', 'restriction_level')
    
    def form_valid(self, form):
        form.instance.registrator = self.request.user
        return super().form_valid(form)
    
    
class PolicyUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Policy
    template_name = 'policies/policy_form_update.html'
    fields = ('perm_dest_ports', 'perm_dest_ips', 'max_size_packet', 'max_data_rate', 'starting_time', 'ending_time', 'restriction_level')

    def test_func(self):
        obj = self.get_object()
        return obj.registrator == self.request.user or self.request.user.is_superuser
    

class PolicyDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Policy
    template_name = 'policies/policy_confirm_delete.html'
    success_url = reverse_lazy('policies:policies')
    
    def test_func(self):
        obj = self.get_object()
        return obj.registrator == self.request.user or self.request.user.is_superuser

policies/templates/policies/base_policies.html
{% extends parent_template|default:"base.html" %}
{% load static %}
{% block css %}{{ block.super }}
  <link rel="stylesheet" href="{% static 'policies/css/policies_base.css' %}">
{% endblock css %}

policies/templates/policies/policy_confirm_delete.html
{% extends parent_template|default:"policies/base_policies.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Delete Policy
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form class="" action="{% url 'policies:policy_delete' policy.pk %}" method="post">
  {% csrf_token %}
  <p>
    Are you sure you want to delete this policy?
  </p>
    <a href="{% url 'policies:policy_detail' policy.pk %}" class="btn btn-primary">Cancel</a>
  <button class="btn btn-danger" type="submit">Delete Policy</button>  
</form>
{% endblock content %}

policies/templates/policies/policy_detail.html
{% extends parent_template|default:"policies/base_policies.html" %}
{% block title %}
{{ block.super }} - Policy {{ policy.pk}}
{% endblock title %} 

{% block css %}{% endblock css %}

{% block content %}
  <div class="container">
    <header>
      <h3 class="text-info">Policy {{ policy.pk }}
          <a href="{% url 'policies:policy_update' policy.pk %}" class="btn btn-warning">Edit</a>
          <a href="{% url 'policies:policy_delete' policy.pk %}" class="btn btn-danger">Delete</a>
      </h3>
  </header>
  </div>
  <hr>
  <div class="container">
    <table class="table table-striped table-dark">
      <tbody>
        <tr>
          <th class="text-info" scope="row">Destination IPs</th>
          <td class="text-success">{{ policy.perm_dest_ips }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Destination Ports</th>
          <td class="text-success">{{ policy.perm_dest_ports }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Destination Ports</th>
          <td class="text-success">{{ policy.perm_dest_ports }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Max Size Packet</th>
          <td class="text-success">{{ policy.max_size_packet }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Max Data Rate</th>
          <td class="text-success">{{ policy.max_data_rate }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Starting Time</th>
          <td class="text-success">{{ policy.starting_time }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Ending Time</th>
          <td class="text-success">{{ policy.ending_time }}</td>
        </tr>
        <tr>
          <th scope="row" class="text-info">Restriction Level</th>
          <td class="text-success">{{ policy.restriction_level }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <hr>
  <div class="container">
    {% if policy.devices.all %}
      <p>
        <h3 class="text-info">Device{{ policy.devices.count|pluralize }}</h3>
        {% for device in policy.devices.all %}
          <li class="text-info list-group-item list-group-item-info"> 
            Manufacturer: {{ device.manufacturer }} |
            Model: {{ device.name }}&nbsp;
              <a href="{% url 'devices:device_detail' device.slug %}" class="btn btn-info">Show</a>
          </li>
        {% endfor %}
      </p>  
    {% else %}
    <p>
      <em class="text-info">No devices have this policy...</em> 
    </p>
    {% endif %}
  </div>    
{% endblock content %}

policies/templates/policies/policy_form.html
{% extends parent_template|default:"policies/base_policies.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Create a New Policy
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form action="{% url 'policies:policy_create' %}" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Create Policy</button>    
</form>

{% endblock content %}

policies/templates/policies/policy_form_update.html
{% extends parent_template|default:"policies/base_policies.html" %}
{% load crispy_forms_tags %}
{% block title %}
{{ block.super }} - Update Policy
{% endblock title %}

{% block css %}{% endblock css %}

{% block content %}
<form action="{{ policy.get_update_url }}" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Update Policy</button>    
</form>

{% endblock content %}

policies/templates/policies/policy_list.html
{% extends parent_template|default:"policies/base_policies.html" %}
{% block title %}
{{ block.super }} - Policies
{% endblock title %}

{% block css %}

{% endblock css %}

{% block content %}
  <p>
    <h5><a href="{% url 'policies:policy_create' %}">+ Add a New Policy</a></h5>
  </p>
  {% for policy in policy_list %}
  <p>
    <h3 class="text-info"> 
      <a href="{{ policy.get_absolute_url }}">Policy {{ policy.pk}}</a>
        <a href="{{ policy.get_update_url }}" class="btn btn-warning">Edit</a>
        <a href="{{ policy.get_delete_url }}" class="btn btn-danger">Delete</a>
    </h3>
  </p>
  <p>
    {% empty %}
      <em class="text-info">No Policies Available...</em>
  </p>  
  {% endfor %}
{% endblock content %}